name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Tests with Maven
      run: mvn -B test --file pom.xml
    - name: Upload Jacoco Site 
      uses: actions/upload-artifact@v4 # GitHub Action that allow to upload on the pipeline result a file or a directory
      with:
        name: jacoco-report
        path: ${{ github.workspace }}/target/site/jacoco
  deliver:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package -DskipTests=true --file pom.xml
    - name: Upload JAR file
      uses: actions/upload-artifact@v4 # GitHub Action that allow to upload on the pipeline result a file or a directory
      with:
        name: jar-file
        path: ${{ github.workspace }}/target/demo*.jar
